baseURL = 'https://rick-torrellas.github.io/book__a'
languageCode = 'es'
title = 'Book'
theme = "tale"
[menu]
  [[menu.main]]
    identifier = "contenido"
    name = "Contenido"
    title = "Contenido"
    url = "/content/"
    weight = 0
  [[menu.main]]
    identifier = "categorias"
    name = "Categorias"
    title = "Categorias"
    url = "/categories/"
    weight = 0
  [[menu.main]]
    identifier = "etiquetas"
    name = "Etiquetas"
    title = "Etiquetas"
    url = "/tags/"
    weight = 0