baseURL = 'https://rick-torrellas.github.io/book__a'
languageCode = 'es'
title = 'Book'
theme = "tale"
[menu]
  [[menu.main]]
    identifier = "contenido"
    name = "Contenido"
    title = "Contenido"
    url = "/content/"
    weight = 0